### ISSUE TITLE
Sensor ID does not match

### ISSUE THREAD

**Issue by ggee** [TheTinkerDad/sensible#7]
I have the following in settings.yaml
```
    - name: Root Disk Free
      kind: script
      sensorid: root_free
      script: root_free.sh
      icon: mdi:harddisk
```

Why is the entity called sensor.root_disk_free?  What is the sensorid for?

**Comment by ggee** [comment]
and in MQTT, it shows this.
```
{
  "name": "Root Disk Free",
  "icon": "mdi:harddisk",
  "state_topic": "homeassistant/sensor/spike/spike_root_free/state",
  "availability_topic": "homeassistant/sensor/spike/availability",
  "payload_available": "Online",
  "payload_not_available": "Offline",
  "unique_id": "spike_root_free",
  "device": {
    "identifiers": [
      "sensible-spike"
    ],
    "manufacturer": "TheTinkerDad",
    "model": "Sensible-Sensor",
    "name": "spike"
  }
}
```
I guess I am quite confused about sensor ID, unique ID and entity ID.

**Comment by TheTinkerDad** [comment]
You've set the device id to "spike", right? So the MQTT you've quoted looks correct.

According to my plans, the entity ID should've ended up like "sensor.spike_root_free" in Home Assistant, but as you've experienced it ends up as "sensor.root_disk_free". If you have two instances of Sensible running with the same config, the sensors will end up as "sensor.root_disk_free" and "sensor.root_disk_free_2" which is clearly not what I wanted.

I should fix this in the next release.

**Comment by TheTinkerDad** [comment]
Got this fixed on the 'latest' branch. Turns out Home Assistant ignores sensor ID and unique ID and instead generates the entity ID from the entity name.

In the new version, sensors will be sent to HA with the entity name consisting of the device name + the sensor name.

E.g. if in your settings.yaml the device name is "sensible-device" and you have a sensor named "My Sensor", in HA a device named "sensible-device" and an entity named "sensor.sensible_device_my_sensor" will be created for that sensor.
